### ISSUE TITLE
Tanti auguri da MozillaItalia

### ISSUE THREAD

**Issue by dag7dev** [MozillaItalia/Idee-della-comunita#1]
Stavo pensando che sarebbe molto carino se ci fosse un modo per inviare una email a chi rende nota / pubblica la sua data di compleanno (da qualche parte) da parte di MozillaItalia.

Una sorta di "buon compleanno" da parte di MozillaItalia, con tanto di immagine di buon compleanno (torta o quant'altro insomma).

Ho già una "bozza" in mente, più tardi aggiorno l'issue!

**Comment by gioxx** [comment]
Mai sopportato quegli automatismi di vari forum e siti web, cosa dovrebbe avere di diverso un eventuale augurio da parte di Mozilla Italia (soprattutto se automatizzato e di sicuro non pensato e scritto per la singola persona)?

**Comment by Sav22999** [comment]
@gioxx E se invece proviamo (almeno come "test pilot") a realizzare messaggi personalizzati? 🤔  (anche a me non piacciono molto le email spam e automatizzate)

**Comment by gioxx** [comment]
Non conosci così bene la persona dall'altro per potertelo permettere, IMHO.
Altra cosa da non sottovalutare: un'altra attività che svolge chi? Si va ad aggiungere alle altre milleduecentocose che si vogliono fare con lo stesso numero di persone a disposizione?

**Comment by dag7dev** [comment]
> 
> 
> Mai sopportato quegli automatismi di vari forum e siti web, cosa dovrebbe avere di diverso un eventuale augurio da parte di Mozilla Italia (soprattutto se automatizzato e di sicuro non pensato e scritto per la singola persona)?

a sentirsi parte più parte di una community ;)
Poi se proponi fare un messaggio personalizzato e te ne vuoi occupare non credo ci siano problemi

**Comment by gioxx** [comment]
Dubito che tu possa sentirti più parte di una community grazie a un'email clonata e mandata a decine di persone differenti.
Leggi poi il mio commento successivo: io vi sto mettendo in guardia dall'usare un automatismo (che alla seconda volta che ti arriva butti nel cestino senza neanche pensarci) e dal fatto che personalizzare la comunicazione richiede uno sforzo che si aggiunge a quanto già c'è da gestire (e tutto il resto che state mettendo in cantiere).

Si rischia di perdere il focus.

**Comment by dag7dev** [comment]
> 
> 
> Dubito che tu possa sentirti più parte di una community grazie a un'email clonata e mandata a decine di persone differenti.
> Leggi poi il mio commento successivo: io vi sto mettendo in guardia dall'usare un automatismo (che alla seconda volta che ti arriva butti nel cestino senza neanche pensarci) e dal fatto che personalizzare la comunicazione richiede uno sforzo che si aggiunge a quanto già c'è da gestire (e tutto il resto che state mettendo in cantiere).
> 
> Si rischia di perdere il focus.

Era comunque un'idea carina siccome al momento chi arriva saluta semplicemente e "torna a dormire" (non parlo ovviamente di tutti ma della maggior parte delle persone).

Magari si potrebbe mandare solo una volta, oppure un'email, uno se la vuole la stampa altrimenti rimane lì / viene eliminata
